# Script for generating figures in SFig7 (simulation study)
# First, we need the results ("../../analysis/simulation/result/cosineDist_epi"),
# generated by the script (""../../analysis/simulation/script/runall_epi.sh").


if (!file.exists("../result/SFig7")) {
  dir.create("../result/SFig7")
}

# script for generating the cosine distances for varying parameters
# output: "../result/SFig7/simulation_result_epi.eps"
source("subscript_SFig7/simulation_result_epi.R")

