# Script for generating figures in SText 1 (simulation study)
# First, we need the results ("../../analysis/simulation/result"),
# generated by the script (""../../analysis/simulation/script/runall.sh").


if (!file.exists("../result/SText1")) {
  dir.create("../result/SText1")
}

# script for generating the cosine distances for varying parameters
# input: the results of "subscript_SText1/simulation_result.R".
# output: "../result/SText1/simulation_result.eps"
source("subscript_SText1/simulation_result.R")


# script for generating the statistics on the simulation study 
# such as likelihood, bootstrap errors, and correlations on signatures,
# and an example of true and estimated signatures.
# input: None
# output: 
source("subscript_SText1/simulation_example_stat_signature.R")

# * the above procedure is not ideal because the statistic information should have been 
# included in the simulaton study results. But I forggot to included it...
# I may fix them iin the future....